// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rupbomfekwkhgoawwacq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cGJvbWZla3draGdvYXd3YWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTI0MTEsImV4cCI6MjA2NDMyODQxMX0.OxSM215bbsQYxaYUjJKng94mP5TzRMNhRAYVYW5sgQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);